# Generated by Django 2.2.6 on 2020-01-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191104_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
