# Generated by Django 2.2.6 on 2020-01-30 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_student_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=120, null=True)),
                ('teacher_name', models.CharField(default=None, max_length=120, null=True)),
                ('exam_time', models.CharField(default=None, max_length=120, null=True)),
                ('exam_day', models.CharField(default=None, max_length=120, null=True)),
                ('daily_time', models.CharField(default=None, max_length=120, null=True)),
                ('semester', models.IntegerField(default=1)),
                ('type', models.IntegerField(default=0)),
                ('major', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Major')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Course')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
