# Generated by Django 2.2.6 on 2020-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200130_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='day',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
