# Generated by Django 2.2.6 on 2020-01-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_course_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
