# Generated by Django 2.2.6 on 2020-02-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='register_id',
            field=models.CharField(default=None, max_length=120, null=True, unique=True),
        ),
    ]
