# Generated by Django 2.2.6 on 2020-02-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_course_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=0),
        ),
    ]
